### ISSUE TITLE
Create "test cases for graphql" issues

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-gw#19]
Create issues for graphql service's test cases
- [x] Graphql queries
    - [x] [auth] #37
    - [x] [roles] #20
    - [x] [errors] #27 
    - [x] [user] #29 
    - [x] [users] #32 
- [x] Graphql mutations
    - [x] [auth] #36 
    - [x] [login] #23
    - [x] [refresh] #24
    - [x] [logout] #25
    - [x] [createUser] #26
    - [x] [updateUserRole] #28
    - [x] [updateUserBase] #30
    - [x] [updateUserStatus] #31
    - [x] [deleteUser] #33
    - [x] [changeUserPassword] #34
    
Our team consist of 11 people ( +2 jr ). We need to assign this endpoints to our teammates in a suitable manner.

**Comment by Sddilora** [comment]
@husamettinarabaci, there is a "Don't use" phrase in the auth query and mutation. What does that mean, and should we also test this field?

![image](https://github.com/octoposprime/op-be-graphql/assets/122971619/aec0d2e2-40d7-4651-8d78-77e22adc4c03)

**Comment by Sddilora** [comment]
**Query :**
```
query getRoles {
  roles(
    filter:{
      RoleName:"USER"
    }
  ){
    RoleName
    PermissionGroups{
      GroupName
      Permissions{
        Policy
      }
    }
  }
}
```
**Output :**

```
{
  "data": {
    "roles": [
      {
        "RoleName": "USER",
        "PermissionGroups": [
          {
            "GroupName": "none",
            "Permissions": [
              {
                "Policy": "none"
              }
            ]
          },
          {
            "GroupName": "user.viewer",
            "Permissions": [
              {
                "Policy": "user.read"
              },
              {
                "Policy": "user.list"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

I'm unsure about that part. The "none" field is returned in all roles. Is this intentional or is it a bug?
```
          {
            "GroupName": "none",
            "Permissions": [
              {
                "Policy": "none"
              }
            ]
          },
```

**Comment by husamettinarabaci** [comment]
> @husamettinarabaci, there is a "Don't use" phrase in the auth query and mutation. What does that mean, and should we also test this field?
> 
> ![image](https://private-user-images.githubusercontent.com/122971619/318568930-aec0d2e2-40d7-4651-8d78-77e22adc4c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDEzNDMsIm5iZiI6MTcxMjE0MTA0MywicGF0aCI6Ii8xMjI5NzE2MTkvMzE4NTY4OTMwLWFlYzBkMmUyLTQwZDctNDY1MS04ZDc4LTc3ZTIyYWRjNGMwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMDQ0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjU1ZDMwN2E5ZTVjYTZhMGI0NGNjMTBhMjU0ZDEwMGE1NmM0MmZiNTUwOWIzMDk2OGFjN2E2NWZkN2E0OTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n-YrPMmdWhv_vJtFqUqjkcpbahOlOIYj6U1K65z7wT0)

It is only middleware for authorization. You can't test it. It is not important.

**Comment by Sddilora** [comment]
desired issues created
