### ISSUE TITLE
Test "login" mutation

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-gw#23]
Test the "login" mutation with all possible cases and create an issue if any bugs are found. If you encounter unexpected behavior or are unsure if it is intended, please create an issue for that as well.

**You can find an example issue and bug report (or a question if this is a bug) in [this link](https://github.com/octoposprime/op-be-graphql/issues/20).**

"[Test GraphQL Query and Mutation](https://github.com/octoposprime/op-be-graphql/discussions/35)" guide is available for further assistance.

**Comment by husamettinarabaci** [comment]
Please add a correct estimated time.

**Comment by Maraza25** [comment]
- Tested with correct username and password.
- Tested with wrong username and password.
- Tested with different username and different password.
- Simple SQL injection tests were performed.

All tests were passed successfully.

**Comment by ebrarkesici** [comment]
I also tried this issue in graphql, made this query and the result was like this:
``````
mutation login{
  login(loginRequest:{
    UserName:"op_admin"
    Email:"op_admin@op.com"
    Password:"opopopop"
  }){
    AuthenticationToken
    RefreshToken
  }
}
``````

``````
{
  "data": {
    "login": {
      "AuthenticationToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWNlZTY2YTYtODc4OC00N2JhLWI1M2UtYzBmYjNhYjI5NzIyIiwiZGF0YSI6eyJpZCI6IjljZWU2NmE2LTg3ODgtNDdiYS1iNTNlLWMwZmIzYWIyOTcyMiIsInVzZXJfbmFtZSI6Im9wX2FkbWluIiwiZW1haWwiOiJvcF9hZG1pbkBvcC5jb20iLCJyb2xlIjoiQURNSU4iLCJ1c2VyX3R5cGUiOjEsInVzZXJfc3RhdHVzIjoxLCJ0YWdzIjpudWxsLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiY3JlYXRlZF9hdCI6IjAwMDEtMDEtMDFUMDA6MDA6MDBaIiwidXBkYXRlZF9hdCI6IjIwMjQtMDQtMDZUMDA6NTE6NTUuMzc1MDIxKzAzOjAwIn0sImV4cCI6MTcxNTE3Njg0MH0.h0B2z14Y9Bj7s20mHRhgjROr1-q6UeZXtwAAUm_CWQU",
      "RefreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWNlZTY2YTYtODc4OC00N2JhLWI1M2UtYzBmYjNhYjI5NzIyIiwiZXhwIjoxNzE3MTY0MDQwfQ.MTClowWDHqslH95RooXNd9D0Dl7LnjGib59RlZGVmgw"
    }
  }
}
``````

login mutation works without any problems
