### ISSUE TITLE
Test "logout" mutation

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-gw#25]
Test the "logout" mutation with all possible cases and create an issue if any bugs are found. If you encounter unexpected behavior or are unsure if it is intended, please create an issue for that as well.

**You can find an example issue and bug report (or a question if this is a bug) in [this link](https://github.com/octoposprime/op-be-graphql/issues/20).**

"[Test GraphQL Query and Mutation](https://github.com/octoposprime/op-be-graphql/discussions/35)" guide is available for further assistance.

**Comment by ebrarkesici** [comment]
I wrote logout code and query user code in graphql.
```graphql
mutation LogoutUser {
  logout(token: {
    AuthenticationToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWNlZTY2YTYtODc4OC00N2JhLWI1M2UtYzBmYjNhYjI5NzIyIiwiZGF0YSI6eyJpZCI6IjljZWU2NmE2LTg3ODgtNDdiYS1iNTNlLWMwZmIzYWIyOTcyMiIsInVzZXJfbmFtZSI6Im9wX2FkbWluIiwiZW1haWwiOiJvcF9hZG1pbkBvcC5jb20iLCJyb2xlIjoiQURNSU4iLCJ1c2VyX3R5cGUiOjEsInVzZXJfc3RhdHVzIjoxLCJ0YWdzIjpudWxsLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiY3JlYXRlZF9hdCI6IjAwMDEtMDEtMDFUMDA6MDA6MDBaIiwidXBkYXRlZF9hdCI6IjIwMjQtMDQtMDZUMDA6NTE6NTUuMzc1MDIxKzAzOjAwIn0sImV4cCI6MTcxNTI3NDY2Nn0.ZVpkJhT_BIFu7C92sRwmaxLgQLnZOCVg5niWUTSTOts",
    RefreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWNlZTY2YTYtODc4OC00N2JhLWI1M2UtYzBmYjNhYjI5NzIyIiwiZXhwIjoxNzE3MjYxODY2fQ.iHo4rPftHTG7J0Ob4xlLCGGSgDRJ8z_d1e1gR7xCX_Y"
  })
}
```
```graphql
query users{
  users(filter:{
    Id:"9cee66a6-8788-47ba-b53e-c0fb3ab29722"
  }){
    Total
    Users{
      Id
      UserName
      Role
      Email
      UserType
      UserStatus
    }
  }
}
```
```json
{
  "data": {
    "logout": true
  }
}
``````
I get results like this.
![Screenshot 2024-05-08 204642](https://github.com/octoposprime/op-be-graphql/assets/141298599/a2790b3b-41ee-4d5e-b41a-9b724f081be5)
I also get a "logout succeeded" message in pgadmin.
