### ISSUE TITLE
Test "createUser" mutation

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-gw#26]
Test the "createUser" mutation with all possible cases and create an issue if any bugs are found. If you encounter unexpected behavior or are unsure if it is intended, please create an issue for that as well.

**You can find an example issue and bug report (or a question if this is a bug) in [this link](https://github.com/octoposprime/op-be-graphql/issues/20).**

"[Test GraphQL Query and Mutation](https://github.com/octoposprime/op-be-graphql/discussions/35)" guide is available for further assistance.

**Comment by ebrarkesici** [comment]
I wrote createuser mutation in graphql. I gave variable and created a new user.
``````graphql
mutation CreateUser($userInput: UserInput!) {
  createUser(user: $userInput) {
    Id
    UserName
    Email
    Role
    UserType
    UserStatus
  }
}
``````
``````graphql
{
  "userInput": {
    "UserName": "ebrarkesici2",
    "Email": "ebrar2@ebrar.com",
    "Role": "USER",
    "UserType": "USER",
    "UserStatus": "ACTIVE"
  }
}
``````
The output is like this:
``````graphql
{
  "data": {
    "createUser": {
      "Id": "60db1db6-c3be-47bc-a90f-82f1e216d97f",
      "UserName": "ebrarkesici2",
      "Email": "ebrar2@ebrar.com",
      "Role": "USER",
      "UserType": "USER",
      "UserStatus": "ACTIVE"
    }
  }
}
``````
![Screenshot 2024-05-11 163657](https://github.com/octoposprime/op-be-graphql/assets/141298599/ffc957eb-2682-4273-8678-83167948993e)
