### ISSUE TITLE
Test "updateUserRole" mutation

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-gw#28]
Test the "updateUserRole" mutation with all possible cases and create an issue if any bugs are found. If you encounter unexpected behavior or are unsure if it is intended, please create an issue for that as well.

**You can find an example issue and bug report (or a question if this is a bug) in [this link](https://github.com/octoposprime/op-be-graphql/issues/20).**

"[Test GraphQL Query and Mutation](https://github.com/octoposprime/op-be-graphql/discussions/35)" guide is available for further assistance.

**Comment by ebrarkesici** [comment]
The code I wrote for the update user role is like this:

```graphql
mutation UpdateUserRole {
  updateUserRole(user: { 
    Id: "9cee66a6-8788-47ba-b53e-c0fb3ab29722", 
    Role: "MANAGER" 
  }) {
    Id
    UserName
    Role
  }
}
```
The error I get is like this:

```json
{
  "errors": [
    {
      "message": "error.user.unauthorized",
      "path": [
        "updateUserRole"
      ]
    }
  ],
  "data": null
}
```

I'm getting an error due to authorization. I may have written the code wrong, I'm not sure.
