### ISSUE TITLE
Test "user" query

### ISSUE THREAD

**Issue by Feyzanrs** [octoposprime/op-be-gw#29]
Test the "user" query with all possible cases and create an issue if any bugs are found. If you encounter unexpected behavior or are unsure if it is intended, please create an issue for that as well.

You can find an example issue and bug report (or a question if this is a bug) in https://github.com/octoposprime/op-be-graphql/issues/20.

"[Test GraphQL Query and Mutation](https://github.com/octoposprime/op-be-graphql/discussions/35)" guide is available for further assistance.

**Comment by ebrarkesici** [comment]
```graphql
mutation login{
  login(loginRequest:{
    UserName:"op_manager"
    Email:"op_manager@op.com"
    Password:"opopopop"
  }){
    AuthenticationToken
    RefreshToken
  }
}

query users{
  users(filter:{
    Id:"bd202a48-c2fc-4a06-ac6d-e65e4bf1abcb"
  }){
    Total
    Users{
      Id
      UserName
      Role
      Email
      UserType
      UserStatus
    }
  }
}

OUTPUT:
{
  "data": {
    "users": {
      "Total": 1,
      "Users": [
        {
          "Id": "bd202a48-c2fc-4a06-ac6d-e65e4bf1abcb",
          "UserName": "op_guest",
          "Role": "ADMIN",
          "Email": "op_guest@op.com",
          "UserType": "USER",
          "UserStatus": "ACTIVE"
        }
      ]
    }
  }
}
```
I made various queries like this and did not get any errors

**Comment by Sddilora** [comment]
I added the 
![image](https://github.com/octoposprime/op-be-graphql/assets/122971619/4fdd4166-c503-40cb-97b3-b36ee1ea84ef)
 field at the beginning of the code and " ``` " at the end to improve the viewing of the code. ( Edited your comment )
This approach is more efficient for typing your code in areas such as comments, etc

@octoposprime/be @octoposprime/be-tl @octoposprime/be-jr, please consider using this approach.
