### ISSUE TITLE
Test "users" query 

### ISSUE THREAD

**Issue by Feyzanrs** [octoposprime/op-be-gw#32]
Test the "users" query with all possible cases and create an issue if any bugs are found. If you encounter unexpected behavior or are unsure if it is intended, please create an issue for that as well.

You can find an example issue and bug report (or a question if this is a bug) in https://github.com/octoposprime/op-be-graphql/issues/20.

"[Test GraphQL Query and Mutation](https://github.com/octoposprime/op-be-graphql/discussions/35)" guide is available for further assistance.

**Comment by Maraza25** [comment]
Query
```  graphql
query users {
  users(filter: {
    SearchText:"ADMIN"
  }) {
    Total
    Users {
      Id
      UserName
      Email
      Role
      UserType
      UserStatus
      UserBase {
        Tags
        FirstName
        LastName
      }
      UpdatedAt
    }
  }
}
```

I ran this query and although there are 4 users registered in the system whose user type or role is admin, only 1 user returns to me, is there an error in the query or in the `SearchText` filter?  

Result
``` json
{
  "data": {
    "users": {
      "Total": 1,
      "Users": [
        {
          "Id": "9cee66a6-8788-47ba-b53e-c0fb3ab29722",
          "UserName": "op_admin",
          "Email": "op_admin@op.com",
          "Role": "ADMIN",
          "UserType": "ADMIN",
          "UserStatus": "ACTIVE",
          "UserBase": {
            "Tags": [],
            "FirstName": "",
            "LastName": ""
          },
          "UpdatedAt": "2024-04-03T15:07:51.042776Z"
        }
      ]
    }
  }
}
```

**Comment by Sddilora** [comment]
can you create an issue for that @Maraza25
