### ISSUE TITLE
Unable to Perform UpdateUserRole in GraphQL Due to Authorization Issue

### ISSUE THREAD

**Issue by ebrarkesici** [octoposprime/op-be-gw#40]
I am encountering a permission issue while trying to execute the UpdateUserRole mutation in GraphQL. Despite assigning the necessary permissions to the manager role in the code, the operation is still failing with an "unauthorized" error message.

**Comment by Sddilora** [comment]
https://github.com/octoposprime/op-be-graphql/issues/28#issuecomment-2040714361

the graphql mutation and result of the issue

**Comment by Sddilora** [comment]
@husamettinarabaci, we are unsure whether this is a bug or if we are doing something wrong. Can you assist us with this?

**Comment by Sddilora** [comment]
We thought the permissions for updating, deleting, etc. were under our manager's authority, but it seems they belong to the admin.
