### ISSUE TITLE
auth mutation implementation

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-gw#44]
mutation:
```graphql
mutation auth {
  auth
  {
    Auth
  }
}
```

result:
```json
{
  "errors": [
    {
      "message": "internal system error",
      "path": [
        "auth"
      ]
    }
  ],
  "data": null
}
```

terminal output of graphql service:
```bash
not implemented: Auth - auth
```

It seems that we don't have authentication implementation in our service, or something else is causing that problem.

**Comment by husamettinarabaci** [comment]
https://github.com/octoposprime/op-be-graphql/issues/48#issuecomment-2082427868

It is not important. It's behavior is normal.
