### ISSUE TITLE
Auth query implementation

### ISSUE THREAD

**Issue by Feyzanrs** [octoposprime/op-be-gw#48]
Query:
```graphql
query {
  auth {
    Auth
  }
}

```

Result:
```json
{
  "errors": [
    {
      "message": "internal system error",
      "path": [
        "auth"
      ]
    }
  ],
  "data": null
}
```

**Comment by Feyzanrs** [comment]
The 'AuthOps' type and associated 'auth' fields in the GraphQL schema are marked as 'Don't use'; this could indicate that their direct use is not appropriate. Could the issue be stemming from this?

**Comment by husamettinarabaci** [comment]
Yes of course. This EP is used by other EPs for authentication and authorization and this error is a normal situation.
