### ISSUE TITLE
Not able to change admin's own  status.

### ISSUE THREAD

**Issue by mervegonc** [octoposprime/op-be-gw#56]
I don't know if it is a problem, but when I login as  admin account, I cannot change the admin's own status.
mutations and results : https://github.com/octoposprime/op-be-graphql/issues/31

**Comment by Sddilora** [comment]
![Screenshot from 2024-05-02 11-02-39](https://github.com/octoposprime/op-be-graphql/assets/122971619/6c4c4e31-3cc7-4c49-a306-a04ac1acfac4)
![Screenshot from 2024-05-02 11-02-05](https://github.com/octoposprime/op-be-graphql/assets/122971619/422de49c-4c4e-4330-bf9e-c276dc444181)

There are no issues with this case on GraphQL. If you encounter any further problems, please open a new issue or reach out to us for assistance.
